# Generated by Django 5.1.3 on 2024-11-28 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
                ('malzemeler', models.TextField()),
                ('yapilis', models.TextField()),
                ('resim', models.ImageField(blank=True, null=True, upload_to='tarif_resimleri/')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='tarifler.tarif')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
