# Generated by Django 5.1.3 on 2024-11-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifler', '0003_malzeme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='yapilis',
            new_name='tarif',
        ),
    ]
