# Generated by Django 5.1.3 on 2024-12-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifler', '0004_rename_yapilis_tarif_tarif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='malzemeler',
        ),
        migrations.AddField(
            model_name='tarif',
            name='malzemeler',
            field=models.ManyToManyField(related_name='tarifler', to='tarifler.malzeme'),
        ),
    ]
