# Generated by Django 5.1.3 on 2024-12-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifler', '0007_rename_olusturan_tarif_olusturan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='olusturan_id',
            field=models.CharField(max_length=50),
        ),
    ]
