# Generated by Django 5.1.4 on 2024-12-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifler', '0009_alter_tarif_olusturan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='olusturan_id',
            new_name='olusturan',
        ),
    ]
