# Generated by Django 5.1.3 on 2024-12-15 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifler', '0010_rename_olusturan_id_tarif_olusturan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favori_kullanicilari', to='tarifler.tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favori_tarifler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
